### ISSUE TITLE
Adicionar verificação de código no CI.

### ISSUE THREAD

**Issue by luizvnasc** [CodeForCuritiba/onibus-io-backend#11]
@joepreludian tem como adicionarmos algumas verificações de código no CI como cobertura de testes e go report card?
Segue um exemplo de outros projetos que possuo:
```yaml
language: go

go:
    - 1.x
    - '1.10'
    - 1.11.x
    - master
before_install:
    - go get github.com/mattn/goveralls
script:
    - go test ./... -v -covermode=count -coverprofile=coverage.out
    - $GOPATH/bin/goveralls -coverprofile=coverage.out -service=travis-cici
after_script:
    - curl -d "repo=github.com/luizvnasc/gonfig" https://goreportcard.com/checks
```

Também teria que ativar o projeto no coveralls, caso esse seja o app adotado para verificação de cobertura de testes.
